### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by orangemug** [orangemug/isomorphic-git-issue-1855#1]
Hey @jcubic just an FYI the issue in <https://github.com/isomorphic-git/isomorphic-git/issues/1855> seems to be fixed for me now. Here's an example of it working, more detail in the `README.md` in the root of the repo.

Essentially it looks like it was some sub-dependency issue (at least for me). Hope this helps.

**Comment by jcubic** [comment]
What repo? If you know a fix please share it. It would also be nice if you shared it in the issue itself so others can see it.

**Comment by jcubic** [comment]
A sorry, Didn't notice that this is the repo.
